2024-08-06 15:44:10,614 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 99, in register
    email = data['email']
KeyError: 'email'
2024-08-06 15:54:26,334 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 105, in register
    return jsonify({"msg": "User already exists"}), 400
  File "<string>", line 4, in __init__
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 562, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
    self.impl.set(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1277, in set
    value = self.fire_replace_event(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1292, in fire_replace_event
    value = fn(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/events.py", line 2573, in wrap
    return fn(target, *arg)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 326, in set_
    return validator(state.obj(), key, value)
  File "/home/debbie/Documents/Shopmate/Server/models.py", line 31, in validate_email
    assert '@' in address, "Invalid email address"
AssertionError: Invalid email address
2024-08-06 15:55:31,900 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 105, in register
  File "<string>", line 4, in __init__
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 562, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
    self.impl.set(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1277, in set
    value = self.fire_replace_event(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1292, in fire_replace_event
    value = fn(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/events.py", line 2573, in wrap
    return fn(target, *arg)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 326, in set_
    return validator(state.obj(), key, value)
  File "/home/debbie/Documents/Shopmate/Server/models.py", line 31, in validate_email
    assert '@' in address, "Invalid email address"
AssertionError: Invalid email address
2024-08-06 16:02:37,388 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 105, in register
  File "<string>", line 4, in __init__
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 562, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
    self.impl.set(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1277, in set
    value = self.fire_replace_event(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1292, in fire_replace_event
    value = fn(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/events.py", line 2573, in wrap
    return fn(target, *arg)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 326, in set_
    return validator(state.obj(), key, value)
  File "/home/debbie/Documents/Shopmate/Server/models.py", line 31, in validate_email
    if '@' not in address:
AssertionError: Invalid email address
2024-08-06 16:04:42,048 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 105, in register
  File "<string>", line 4, in __init__
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 562, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
    self.impl.set(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1277, in set
    value = self.fire_replace_event(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1292, in fire_replace_event
    value = fn(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/events.py", line 2573, in wrap
    return fn(target, *arg)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 326, in set_
    return validator(state.obj(), key, value)
  File "/home/debbie/Documents/Shopmate/Server/models.py", line 31, in validate_email
    if '@' not in address:
AssertionError: Invalid email address
2024-08-06 17:52:49,815 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (3, testname, testname@gmail.com, null, 2024-08-06 14:52:49.238985, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 109, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (3, testname, testname@gmail.com, null, 2024-08-06 14:52:49.238985, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'testname', 'email': 'testname@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 14, 52, 49, 238985), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-06 18:49:54,008 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (4, johnDoe, johndoe@example.com, null, 2024-08-06 15:49:53.439277, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 110, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (4, johnDoe, johndoe@example.com, null, 2024-08-06 15:49:53.439277, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'johnDoe', 'email': 'johndoe@example.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 15, 49, 53, 439277), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-06 18:52:10,394 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (5, johnDoe, johndoe@example.com, null, 2024-08-06 15:52:09.806996, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 110, in register
    db.session.add(new_user)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (5, johnDoe, johndoe@example.com, null, 2024-08-06 15:52:09.806996, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'johnDoe', 'email': 'johndoe@example.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 15, 52, 9, 806996), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-06 19:19:41,810 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (6, johnDoe, johndoe@example.com, null, 2024-08-06 16:19:41.245982, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 116, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (6, johnDoe, johndoe@example.com, null, 2024-08-06 16:19:41.245982, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'johnDoe', 'email': 'johndoe@example.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 16, 19, 41, 245982), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-06 22:56:27,188 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (11, admin, admin@gmail.com, null, 2024-08-06 19:56:26.415966, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (11, admin, admin@gmail.com, null, 2024-08-06 19:56:26.415966, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 19, 56, 26, 415966), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-06 23:39:15,174 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (12, admin, admin@gmail.com, null, 2024-08-06 20:39:14.452245, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (12, admin, admin@gmail.com, null, 2024-08-06 20:39:14.452245, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 20, 39, 14, 452245), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-06 23:44:39,659 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (13, admin, admin@gmail.com, null, 2024-08-06 20:44:38.999891, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (13, admin, admin@gmail.com, null, 2024-08-06 20:44:38.999891, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 20, 44, 38, 999891), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-07 00:12:11,559 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (14, admin, admin@gmail.com, null, 2024-08-06 21:12:10.810303, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (14, admin, admin@gmail.com, null, 2024-08-06 21:12:10.810303, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 21, 12, 10, 810303), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-07 00:12:47,976 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (15, admin, admin@gmail.com, null, 2024-08-06 21:12:47.288484, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (15, admin, admin@gmail.com, null, 2024-08-06 21:12:47.288484, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 21, 12, 47, 288484), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-07 00:14:25,769 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (16, admin, admin@gmail.com, null, 2024-08-06 21:14:25.006183, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (16, admin, admin@gmail.com, null, 2024-08-06 21:14:25.006183, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 21, 14, 25, 6183), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-07 00:15:30,491 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (17, admin, admin@gmail.com, null, 2024-08-06 21:15:29.268941, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (17, admin, admin@gmail.com, null, 2024-08-06 21:15:29.268941, null, f).

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': None, 'created_at': datetime.datetime(2024, 8, 6, 21, 15, 29, 268941), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-07 00:57:10,477 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (19, admin, admin@gmail.com, null, 2024-08-06 21:57:09.818436, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (19, admin, admin@gmail.com, null, 2024-08-06 21:57:09.818436, null, f).

[SQL: INSERT INTO "user" (username, email, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'created_at': datetime.datetime(2024, 8, 6, 21, 57, 9, 818436), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-07 00:59:33,553 - app - ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (20, admin, admin@gmail.com, null, 2024-08-06 21:59:32.928339, null, f).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "password" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (20, admin, admin@gmail.com, null, 2024-08-06 21:59:32.928339, null, f).

[SQL: INSERT INTO "user" (username, email, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'created_at': datetime.datetime(2024, 8, 6, 21, 59, 32, 928339), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-07 01:08:06,771 - app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(150)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(150)

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': 'scrypt:32768:8:1$2eTKwuOxNpmty6RW$f766943ac5297fed7b063d49de78d8e20a06fcb13ffdf77548a6b00b82b4d945a1ee66d2edd9ba4421a28aea844b6ad2f08ba5c186322dba398461ce4a5188ef', 'created_at': datetime.datetime(2024, 8, 6, 22, 8, 6, 210899), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2024-08-07 01:17:31,592 - app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(150)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 113, in register
    db.session.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(150)

[SQL: INSERT INTO "user" (username, email, password, created_at, preferences, is_admin) VALUES (%(username)s, %(email)s, %(password)s, %(created_at)s, %(preferences)s, %(is_admin)s) RETURNING "user".id]
[parameters: {'username': 'admin', 'email': 'admin@gmail.com', 'password': 'scrypt:32768:8:1$GpfRSIRNnpDJUf0K$87d29fd15449f7612603a4cc95a974caf77364cc82cd08c5bc2e4e8d33985a329965076701f9dcb41abd2286df934ca48a605f0ca0436b973d0e87fa0c25849f', 'created_at': datetime.datetime(2024, 8, 6, 22, 17, 30, 927087), 'preferences': None, 'is_admin': False}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2024-08-07 15:40:52,779 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-07 15:41:17,601 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-07 15:44:42,432 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-07 16:04:54,257 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-07 16:17:36,655 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-07 16:18:54,486 - app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debbie/Documents/Shopmate/Server/app.py", line 107, in register
    email = data['email']
KeyError: 'email'
2024-08-07 16:21:02,509 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-07 16:34:20,914 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-08 17:29:57,058 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
2024-08-08 17:30:34,198 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debbie/.local/share/virtualenvs/Shopmate-pGBVM-KF/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: jwt_required() missing 1 required positional argument: 'fn'
